[package]
name = "object-rainbow-store"
version = "0.0.0-a.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
object-rainbow.workspace = true

[package.metadata.tagit]
skip = true
